// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/looduskosmeetika",

  metadata: {
    title: "Looduskosmeetika juhend",
    description:
      "80 retsepti 100% looduskosmeetika valmistamiseks kodus. Testitud ja ohutud valemid naha hooldamiseks ja mürgiste kemikaalide vältimiseks.",
  },

  hero: {
    headlineLine1: "80 retsepti",
    headlineHighlight: "LOODUSKOSMEETIKA JAOKS",
    subheadline:
      "Saa ligipääs 100% looduskosmeetika salajastele retseptidele, mida saad valmistada mugavalt oma kodus! Testitud ja turvalised valemid, et kaitsta oma perekonda ja loobuda toksiine täis tööstustoodetest.",
    cta: "SOOVIN KOHE LIGIPÄÄSU!",
    imageAlt: "Looduskosmeetika juhend",
    timerLabels: {
      days: "Päeva",
      hours: "Tundi",
      minutes: "Minutit",
      seconds: "Sekundit",
    },
  },

  story: {
    text: "Annan sulle nüüd ühe praktilise juhendi, otse asja juurde, ilma liigse keerukuseta, kuid äärmiselt usaldusväärse, et saaksid luua oma 100% looduskosmeetikat kodus. Ilma varandust kulutamata, sõltumata tuhandetest koostisosadest – ning rõõmuga kasutada seda ise, kinkida oma lähedastele ja nautida koos 100% turvalist ja tervislikku hoolitsust!",
    imageAlt: "Looduskosmeetika",
  },

  recipeList: {
    headline: "Tutvu",
    headlineHighlight: "80 retseptiga,",
    headlineSuffix: "millele saad ligipääsu Looduskosmeetika juhendis:",
    cta: "TAHAN NEID!",
    col1: [
      "Rahustav kehakreem",
      "Pantenooliga kehakreem",
      "Värskendav kehalosjoon",
      "Kehasuflee",
      "Urukuumiga kehavõi",
      "Tahke kehavõi",
      "Kehaõli",
      "Terapeutiline õli pigmendilaikudele ja venitusarmidele",
      "Kahefaasiline kehaõli",
      "Looduslik isepruunistav kreem",
      "Vedelseep kehale",
      "Dušigeel",
      "SCI-ga tahke kehaseep",
      "Traditsiooniline tahke kehaseep",
      "Kreemjas niisutav seep",
      "Kooriv kehaseep (Soap Body Scrub)",
      "Kehakoorija",
      "Mandlijahuga kehakoorija",
      "Looduslik kehasära",
      "Kehasprei (Body Splash)",
      "C-vitamiiniga näokreem",
      "Lavendliga päevitusjärgne näokreem",
      "Saviga näokreem",
      "Niisutav näokreem jasmiiniga",
      "Kuivõli näole (Dry Oil)",
      "Vedel näoseep",
      "Näopesuvaht",
      "Näoseerum kuivale ja tundlikule nahale",
      "Näoseerum rasusele nahale",
      "Silmaseerum",
      "Näotoonik kuivale ja tundlikule nahale",
      "Värskendav näotoonik rasusele nahale",
      "Näopuhastusõli (Cleansing Oil)",
      "Näopuhastuspalsam (Cleansing Balm)",
      "Punase savi seep – detoks ja taaselustamine",
      "Õrn näokoorija",
      "Salitsüülhappega näogeel",
      "Hüaluroonhappega geelmask näole",
      "Roosi näoeliksiir",
      "Aaloe näosprei",
      "Mask lokkis ja lainelistele juustele",
    ],
    col2: [
      "Mask sirgetele ja kergelt lainelistele juustele",
      "Kreemjas palsam",
      "Tahke palsam lokkis ja lainelistele juustele",
      "Tahke palsam kergelt lainelistele ja sirgetele juustele",
      "Tahke šampoon lokkis ja lainelistele juustele",
      "Tahke šampoon sirgetele ja kergelt lainelistele juustele",
      "Vedel šampoon",
      "Kreemjas 2-in-1 šampoon",
      "Lastešampoon",
      "Juustesse jäetav palsam (Leave-In)",
      "Kuumakaitse sprei juustele",
      "Juukseõli",
      "Juuksegeel",
      "Looduslik juuksepumat",
      "Niisutav viimistlussprei",
      "Peanaha koorija",
      "Juuksekasvu soodustav toonik",
      "Seerum lõhenenud otstele",
      "Juukseparfüüm",
      "Looduslik intiimpesugeel",
      "Looduslik lasteseep",
      "Looduslik vedel parfüüm",
      "Looduslik tahke parfüüm",
      "Geeljas hambapasta",
      "Suuvesi",
      "Spreideodorant",
      "Saialillesalv",
      "Arnikasalv",
      "Toitev huulepalsam",
      "Looduslik huulepulk",
      "Looduslik huulekoorija",
      "Meigieemaldussprei",
      "Raseerimisvaht",
      "Looduslik raseerimisjärgne hooldus",
      "Käte- ja jalakreem",
      "Kulmude fikseerimisgeel",
      "Looduslik massaažiküünal",
      "Toitev seerum küüntele ja küünenahkadele",
      "Looduslik putukatõrjevahend",
      "Taaselustavad vannisoolad",
    ],
  },

  whatYouGet: {
    headline: "MIDA LEIAD SELLEST ERAKORDSEST JUHENDIST?",
    cta: "HANGI JUHEND KOHE!",
    imageAlt: "Mida juhendist leiad",
    items: [
      "Üle 80 testitud ja tõestatud retsepti – sealhulgas kreemjas kooriv seep, kuivõli näole, kehasprei, juuste kuumakaitse ja arvukalt uusi, innovaatilisi valemeid.",
      "Baasretseptid kreemidele, geelidele, šampoonidele ja seepidele – õpi looma 100% ohutuid ja isikupärastatud tooteid igale naha- ja juuksetüübile.",
      "Täielik samm-sammuline juhend algajatele ja edasijõudnutele – omanda kõike alates põhimõistetest kuni kõige keerukamate kosmeetika valmistamise tehnikateni.",
      "Koostisosade kataloog – avasta erinevate looduslike toorainete eelised, et luua kvaliteetset ja puhast kosmeetikat.",
      "Fütoterapie rakendamine kosmetoloogias – kuidas kasutada ravimtaimi oma kosmeetika toime maksimaalseks tugevdamiseks.",
      "Loodusliku formuleerimise saladused – pH reguleerimine, looduslik säilitamine, tooraine valik ja kõige tõhusamad kombinatsioonid.",
      "Nõuanded täiuslikuks koduseks tootmiseks – muuda oma köök turvaliseks kohaks puhta kosmeetika loomiseks ja täiusta oma oskusi.",
      "Jätkusuutlikkus ja keskkonnahoid – õpi looma täielikult biolagunevat ja planeedisõbralikku kosmeetikat.",
    ],
  },

  testimonials: {
    headline: "VAATA, MIDA ÜTLEVAD NAISED, KES SEDA JUHENDIT JUBA KASUTAVAD:",
    cta: "LIITU NENDEGA!",
    cards: [
      {
        name: "Maarja S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Ma armastan seda juhendit! Tegin juba rahustava kehakreemi ja näoseebi – need tulid imelised. Palju paremad kui tööstuslikud tooted, mida varem kasutasin. Soovitan soojalt kõigile!",
        source: "WhatsApp",
      },
      {
        name: "Kadri T.",
        initials: "KT",
        color: "#0f766e",
        stars: 5,
        text: "Naised, see on lihtsalt suurepärane juhend! Retseptid on väga detailsed ja neid on lihtne järgida. Tegin juba mitu toodet sõbrannadele kingituseks ja nad on vaimustuses. Väärt iga senti!",
        source: "WhatsApp",
      },
      {
        name: "Liis M.",
        initials: "LM",
        color: "#7c3aed",
        stars: 5,
        text: "Ma alguses veidi kõhklesin ostmisel, aga see oli kindlasti seda väärt! Toorainete kataloog aitas mul koostisosi palju paremini mõista. Olen juba teinud 6 erinevat retsepti ja kõik on veatult õnnestunud.",
        source: "WhatsApp",
      },
      {
        name: "Triin K.",
        initials: "TK",
        color: "#b45309",
        stars: 5,
        text: "Milline suurepärane investeering! Selle juhendi abil õppisin lõpuks tegema tahket šampooni ja palsamit. Mu juuksed on elujõulisemad, palju tervislikumad ja ma säästan iga kuu kosmeetika pealt korralikult raha. Aitäh!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Looduskosmeetika juhendiga õpid looma oma tooteid täiesti nullist.",
    text2: "See näitab sulle samm-sammult, kuidas teadlikult valida looduslikke koostisosi, kohandada valemeid vastavalt naha tüübile või juuste poorsusele ning isikupärastada tooteid nii, et need vastaksid ideaalselt sinu vajadustele.",
    text3: "Saavutad enesekindluse ja täieliku iseseisvuse formuleerimises. Saad retsepte testida ja täiustada, luues ainulaadset ja oma iseloomuga kosmeetikat. Tänu eriti põhjalikule looduslike toorainete kataloogile õpid tundma parimaid koostisosi ja leiad ideaalsed kombinatsioonid iga tooteliigi jaoks.",
    cta: "HANGI JUHEND!",
    imageAlt: "Iseseisvus looduskosmeetika valmistamisel",
  },

  benefitsList: {
    headline: "Sõltumatus ja loovus loodusliku hoolitsuse maailmas!",
    cta: "SOOVIN KOHE LIGIPÄÄSU!",
    items: [
      {
        bold: "Õpi valmistama",
        rest: " kreeme, seerumeid, šampoone, seepe ja paljusid muid hooldustooteid.",
      },
      {
        bold: "Avasta, kuidas eksimatult valida",
        rest: " õigeid koostisosi naha ja juuste iga spetsiifilise vajaduse jaoks.",
      },
      {
        bold: "Vabane tööstuslikust keemiast ja",
        rest: " arenda välja 100% personaalsed, looduslikud valemid.",
      },
      {
        bold: "Sukeldu kosmetoloogias rakendatavasse fütoteraapiasse,",
        rest: " saades osa ravimtaimede ja ekstraktide tervendavatest omadustest.",
      },
      {
        bold: "Vähenda oluliselt oma kulusid,",
        rest: " luues ise oma kosmeetikat ilma selle kvaliteedis vähimatki järeleandmist tegemata.",
      },
      {
        bold: "Saa ligipääs professionaalsetele retseptidele",
        rest: " ja õpi turvaliselt looma tipptasemel tooteid.",
      },
      {
        bold: "Paku oma nahale parimat hoolitsust,",
        rest: " teades täpselt, milliseid puhtaid koostisosi sa kasutad.",
      },
      {
        bold: "Kaitse oma pere tervist",
        rest: " toodetega, mis on vabad kahjulikest säilitusainetest ja kunstlikest värvainetest.",
      },
    ],
  },

  economy: {
    headline: "Säästmine ja tervislik hooldus ilma ainsagi grammi keemiata!",
    text1: "Oma looduskosmeetika loomine on parim viis naha kaitsmiseks ja samal ajal tohutult raha säästmiseks. Looduskosmeetika juhendiga õpid valmistama tippkvaliteediga tooteid vaid murdosa eest poehinnast. Nii väldid ülemaksmist keemiat täis laiatarbekosmeetika eest ja investeerid taskukohastesse, puhastesse ja väga tõhusatesse looduslikesse toorainetesse.",
    text2: "See on sinu hindamatu käsiraamat tervislikumale elustiilile üleminekul. Tänu eksklusiivsetele retseptidele saad tagasi täieliku kontrolli selle üle, mida oma kehale määrid. Saad nautida käsitöötooteid, mis on 100% ohutud, ökoloogilised ja õrnad nii sinu naha kui ka keskkonna vastu.",
    cta: "ALUSTAN VALMISTAMIST!",
    imageAlt: "Tervislik hoolitsus",
  },

  finalCta: {
    urgencyLabel: "VIIMANE PÄEV TELLIMISEKS",
    urgencySub: "soodus- ja kampaaniahinnaga!",
    urgencyText:
      "See on sinu absoluutselt viimane võimalus kasutada meie erakordset pakkumist ja liituda tuhandete vaimustunud õpilastega!",
    offerPrice: "9.90 €",
    button: "SAA LIGIPÄÄS KOHE!",
    productTitle: "Looduskosmeetika juhend!",
    imageAlt: "Looduskosmeetika juhend",
    bundleList: [
      "80 looduskosmeetika retsepti",
      "Põhjalik samm-sammuline käsiraamat",
      "Toorainete õpetlik leksikon",
      "Ligipääs suletud kogukonnale",
      "Ekspertide tugi kõikidele küsimustele",
      "Kontrollitud ja usaldusväärne tarnijate nimekiri",
    ],
    timerLabels: {
      days: "Päeva",
      hours: "Tundi",
      minutes: "Minutit",
      seconds: "Sekundit",
    },
  },

  footer: {
    tagline: "Avasta koos meiega, kuidas luua täiuslikku looduskosmeetikat!",
  },
};