// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/kozmetika-naturalna",

  metadata: {
    title: "Looduskosmeetika juhend | PerfuMaria das Ervas",
    description:
      "80 retsepti 100% looduskosmeetika valmistamiseks kodus. Testitud ja tõestatud valemid isiklikuks kasutamiseks või oma äri alustamiseks.",
  },

  hero: {
    headlineLine1: "80 retsepti",
    headlineHighlight: "LOODUSKOSMEETIKA JAOKS",
    subheadline:
      "Saa ligipääs 100% looduskosmeetika salajastele retseptidele, mida saad valmistada mugavalt oma kodus! Testitud ja tõestatud valemid isiklikuks kasutamiseks või oma äri alustamiseks.",
    cta: "SOOVIN KOHE LIGIPÄÄSU!",
    imageAlt: "Looduskosmeetika juhend",
    timerLabels: {
      days: "Päeva",
      hours: "Tundi",
      minutes: "Minutit",
      seconds: "Sekundit",
    },
  },

  story: {
    text: "Annan sulle nüüd ühe praktilise juhendi, otse asja juurde, ilma liigse keerukuseta, kuid äärmiselt usaldusväärse, et saaksid luua oma 100% looduskosmeetikat kodus. Ilma varandust kulutamata, sõltumata tuhandetest koostisosadest – ja võimalusega kasutada seda ise, kinkida oma lähedastele või isegi müüa, kui soovid luua uue sissetulekuallika!",
    imageAlt: "Looduskosmeetika",
  },

  recipeList: {
    headline: "Tutvu",
    headlineHighlight: "80 retseptiga,",
    headlineSuffix: "millele saad ligipääsu Looduskosmeetika juhendis:",
    cta: "TAHAN NEID!",
    col1: [
      "Rahustav kehakreem",
      "Pantenooliga kehakreem",
      "Värskendav kehalosjoon",
      "Kehasuflee",
      "Urukuumiga kehavõi",
      "Tahke kehavõi",
      "Kehaõli",
      "Terapeutiline õli pigmendilaikudele ja venitusarmidele",
      "Kahefaasiline kehaõli",
      "Looduslik isepruunistav kreem",
      "Vedelseep kehale",
      "Dušigeel",
      "SCI-ga tahke kehaseep",
      "Traditsiooniline tahke kehaseep",
      "Kreemjas niisutav seep",
      "Kooriv kehaseep (Soap Body Scrub)",
      "Kehakoorija",
      "Mandlijahuga kehakoorija",
      "Looduslik kehasära",
      "Kehasprei (Body Splash)",
      "C-vitamiiniga näokreem",
      "Lavendliga päevitusjärgne näokreem",
      "Saviga näokreem",
      "Niisutav näokreem jasmiiniga",
      "Kuivõli näole (Dry Oil)",
      "Vedel näoseep",
      "Näopesuvaht",
      "Näoseerum kuivale ja tundlikule nahale",
      "Näoseerum rasusele nahale",
      "Silmaseerum",
      "Näotoonik kuivale ja tundlikule nahale",
      "Värskendav näotoonik rasusele nahale",
      "Näopuhastusõli (Cleansing Oil)",
      "Näopuhastuspalsam (Cleansing Balm)",
      "Punase savi seep – detoks ja taaselustamine",
      "Õrn näokoorija",
      "Salitsüülhappega näogeel",
      "Hüaluroonhappega geelmask näole",
      "Roosi näoeliksiir",
      "Aaloe näosprei",
      "Mask lokkis ja lainelistele juustele",
    ],
    col2: [
      "Mask sirgetele ja kergelt lainelistele juustele",
      "Kreemjas palsam",
      "Tahke palsam lokkis ja lainelistele juustele",
      "Tahke palsam kergelt lainelistele ja sirgetele juustele",
      "Tahke šampoon lokkis ja lainelistele juustele",
      "Tahke šampoon sirgetele ja kergelt lainelistele juustele",
      "Vedel šampoon",
      "Kreemjas 2-in-1 šampoon",
      "Lastešampoon",
      "Juustesse jäetav palsam (Leave-In)",
      "Kuumakaitse sprei juustele",
      "Juukseõli",
      "Juuksegeel",
      "Looduslik juuksepumat",
      "Niisutav viimistlussprei",
      "Peanaha koorija",
      "Juuksekasvu soodustav toonik",
      "Seerum lõhenenud otstele",
      "Juukseparfüüm",
      "Looduslik intiimpesugeel",
      "Looduslik lasteseep",
      "Looduslik vedel parfüüm",
      "Looduslik tahke parfüüm",
      "Geeljas hambapasta",
      "Suuvesi",
      "Spreideodorant",
      "Saialillesalv",
      "Arnikasalv",
      "Toitev huulepalsam",
      "Looduslik huulepulk",
      "Looduslik huulekoorija",
      "Meigieemaldussprei",
      "Raseerimisvaht",
      "Looduslik raseerimisjärgne hooldus",
      "Käte- ja jalakreem",
      "Kulmude fikseerimisgeel",
      "Looduslik massaažiküünal",
      "Toitev seerum küüntele ja küünenahkadele",
      "Looduslik putukatõrjevahend",
      "Taaselustavad vannisoolad",
    ],
  },

  whatYouGet: {
    headline: "MIDA LEIAD SELLEST TÄIUSLIKUST JUHENDIST?",
    cta: "HANGI JUHEND KOHE!",
    imageAlt: "Mida juhendist leiad",
    items: [
      "Üle 80 testitud ja tõestatud retsepti – sealhulgas kreemjas kooriv seep, kuivõli näole, kehasprei, juuste kuumakaitse ja mitmekülgsed uued valemid.",
      "Baasretseptid kreemidele, geelidele, šampoonidele ja seepidele – õpi looma ohutuid ja personaalseid valemeid igale naha- ja juuksetüübile.",
      "Täielik samm-sammuline juhend algajatele ja edasijõudnutele – omanda kõike alates põhikontseptsioonidest kuni kõige keerukamate tehnikateni.",
      "Koostisosade kataloog – avasta erinevate looduslike toorainete eelised, et luua väga tõhusat kosmeetikat.",
      "Fütoteraapia rakendamine kosmetoloogias – kuidas kasutada ravimtaimi oma kosmeetika toime tugevdamiseks.",
      "Loodusliku formuleerimise saladused – pH reguleerimine, säilitamine, tooraine valik ja tõhusad kombinatsioonid.",
      "Nõuanded koduseks ja professionaalseks tootmiseks – loo oma looduskosmeetika stuudio ja täiusta oma tehnikaid.",
      "Jätkusuutlikkus ja keskkonnahoid – õpi looma biolagunevat ja keskkonnasõbralikku kosmeetikat.",
    ],
  },

  testimonials: {
    headline: "VAATA, MIDA INIMESED LOODUSKOSMEETIKA JUHENDI KOHTA ÜTLEVAD:",
    cta: "SOOVIN KOHE LIGIPÄÄSU!",
    cards: [
      {
        name: "Maarja S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Ma armastan seda juhendit! Tegin juba rahustava kehakreemi ja näoseebi ning need tulid imelised. Palju paremad kui poest ostetud tooted, mida varem kasutasin. Soovitan soojalt!",
        source: "WhatsApp",
      },
      {
        name: "Kadri T.",
        initials: "KT",
        color: "#0f766e",
        stars: 5,
        text: "Kuulge, see on lihtsalt suurepärane juhend! Retseptid on väga detailsed ja neid on lihtne jälgida. Olen juba mitu toodet sõbrannadele müünud ja nad fännavad neid. Väärt iga senti!",
        source: "WhatsApp",
      },
      {
        name: "Liis M.",
        initials: "LM",
        color: "#7c3aed",
        stars: 5,
        text: "Ma alguses veidi kõhklesin ostmisel, aga see oli kindlasti seda väärt! Toorainete kataloog aitas mul koostisosi palju paremini mõista. Olen juba teinud 6 erinevat retsepti ja kõik on suurepäraselt õnnestunud.",
        source: "WhatsApp",
      },
      {
        name: "Triin K.",
        initials: "TK",
        color: "#b45309",
        stars: 5,
        text: "Milline uskumatu investeering! Selle juhendi abil õppisin tegema tahket šampooni ja palsamit. Mu juuksed on palju tervemad ja ma säästan iga kuu korralikult raha. Suur tänu!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Looduskosmeetika juhendiga õpid looma oma kosmeetikat nullist.",
    text2: "See näitab sulle samm-sammult, kuidas valida looduslikke koostisosi, kohandada valemeid erinevatele naha- ja juuksetüüpidele ning isikupärastada tooteid vastavalt sinu vajadustele.",
    text3: "Lisaks saavutad enesekindluse ja iseseisvuse formuleerimises, olles võimeline retsepte testima ja kohandama, et luua unikaalseid, oma identiteediga tooteid. Tänu põhjalikule looduslike toorainete kataloogile õpid tundma parimaid koostisosi ja leiad ideaalse kombinatsiooni iga kosmeetikatoote jaoks.",
    cta: "HANGI JUHEND KOHE!",
    imageAlt: "Iseseisvus looduskosmeetikas",
  },

  benefitsList: {
    headline: "Sõltumatus ja loovus looduskosmeetikas!",
    cta: "SOOVIN KOHE LIGIPÄÄSU!",
    items: [
      {
        bold: "Õpi valmistama",
        rest: " kreeme, seerumeid, šampoone, seepe ja palju muud.",
      },
      {
        bold: "Avasta, kuidas valida",
        rest: " õigeid koostisosi igaks vajaduseks.",
      },
      {
        bold: "Muutu sõltumatuks tööstuslikust kosmeetikast ja",
        rest: " arenda välja personaalseid valemeid.",
      },
      {
        bold: "Sukeldu kosmetoloogias rakendatavasse fütoteraapiasse,",
        rest: " kasutades ära ravimtaimede terapeutilisi omadusi.",
      },
      {
        bold: "Vähenda kulusid,",
        rest: " luues ise oma kosmeetikat ilma kvaliteedis järeleandmisi tegemata.",
      },
      {
        bold: "Saa ligipääs professionaalsetele valemitele",
        rest: " ja õpi looma parimaid tooteid ohutult.",
      },
      {
        bold: "Eristu loodusilu turul,",
        rest: " mis kasvab järjest enam ja väärtustab jätkusuutlikke tooteid.",
      },
      {
        bold: "Õpi üles seadma kodust kosmeetikastuudiot,",
        rest: " koos praktiliste nõuannetega tööruumi korraldamiseks.",
      },
    ],
  },

  economy: {
    headline: "Säästud ja ärivõimalus looduskosmeetika turul!",
    text1: "Oma looduskosmeetika loomine on suurepärane võimalus nii raha säästmiseks kui ka äri alustamiseks. Looduskosmeetika juhendiga õpid tootma kvaliteetset kosmeetikat madalate kuludega, vältides tavatoodete ülemääraseid hindu ja investeerides taskukohastesse ning tõhusatesse looduslikesse koostisosadesse.",
    text2: "Kui soovid alustada oma ettevõtlusega, on see väärtuslik teejuht jätkusuutliku ja kasumliku äri loomisel. Eksklusiivsete valemite ning praktiliste nõuannetega säilitamise, pakendamise ja turunduse kohta saad luua oma looduskosmeetika brändi, pakkudes käsitöötooteid, mis järgivad teadliku ja ökoloogilise tarbimise trendi.",
    cta: "HANGI JUHEND KOHE!",
    imageAlt: "Äri looduskosmeetika turul",
  },

  finalCta: {
    urgencyLabel: "VIIMANE PÄEV TELLIMISEKS",
    urgencySub: "soodushinnaga!",
    urgencyText:
      "See on sinu viimane võimalus kasutada meie eripakkumist ja liituda meie tuhandetest rahulolevatest õpilastest koosneva perega!",
    offerPrice: "9.90 €",
    button: "SAA LIGIPÄÄS KOHE!",
    productTitle: "Looduskosmeetika juhend!",
    imageAlt: "Looduskosmeetika juhend",
    bundleList: [
      "80 looduskosmeetika retsepti",
      "Põhjalik õppematerjal",
      "Toorainete hariv kataloog",
      "Õpilaste kogukond",
      "Spetsiaalne tugi küsimuste korral",
      "Tarnijate nimekiri",
    ],
    timerLabels: {
      days: "Päeva",
      hours: "Tundi",
      minutes: "Minutit",
      seconds: "Sekundit",
    },
  },

  footer: {
    tagline: "Avasta, kuidas luua täiuslikku looduskosmeetikat!",
    linkLabel: "Täielik looduskosmeetika kursus",
    linkHref: "https://www.perfumariadaservas.shop",
  },
};